### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_dropout: 0.1

### dataset
dataset: cogs
template: llama3
cutoff_len: 1024
#max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
train_on_prompt: true

### output
output_dir: saves/llama3-8b/cogs_base/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-5
num_train_epochs: 5
lr_scheduler_type: cosine
warmup_ratio: 0
bf16: true
ddp_timeout: 180000000

### eval
#val_size: 0.1
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 500
